demo.chat:
    channel: /chat
    handler:
        callback: 'chat.rpc' #related to the getName() or your RPC service
pm.chat:
    channel: /pm/public
    handler:
        callback: 'chat.rpc' #related to the getName() or your RPC service