Application\FormsBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: Application\FormsBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
